### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by gremlin97** [littleosbook/aenix#4]
-I am getting this error while running makefile.Please solve this as soon as possible as I am doing a project on this. 
-> Building kernel
make[1]: Nothing to be done for 'all'.

-> Building libc
make[1]: Nothing to be done for 'all'.

-> Building applications
ld -T link.ld -melf_i386 init.o -L../libc -lc -o init
init.o: In function `main':
init.c:(.text+0x19): undefined reference to `_GLOBAL_OFFSET_TABLE_'
Makefile:15: recipe for target 'init' failed
make[1]: *** [init] Error 1
Makefile:50: recipe for target 'build_apps' failed
make: *** [build_apps] Error 2

**Comment by NemanjaMilosevic** [comment]
If you take a look at main make file, you will see it has no rule for all. Its just make.

**Comment by rrmhearts** [comment]
I'm seeing this same issue. Have you found a solution?

**Comment by esarver** [comment]
On Fedora 27 I'm getting a segmentation fault at the same place. Maybe this should be a separate issue, but it is at the same place in the build. Any thoughts? 

```
-> Building libc
nasm -f elf unistd.s -o unistd.o
nasm -f elf start.s -o start.o
gcc -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -nostartfiles -nodefaultlibs -Wall -Wextra -Werror -Wno-unused-function -c string.c -o string.o
ar rcs libc.a unistd.o start.o string.o

gcc -Wall -Wextra -Werror -m32 mkfs.c -o mkfs
-> Building applications
gcc -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -nostartfiles -nodefaultlibs -Wall -Wextra -Werror -Wno-unused-function -c -I../libc init.c -o init.o
ld -T link.ld -melf_i386 init.o -L../libc -lc -o init
gcc -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -nostartfiles -nodefaultlibs -Wall -Wextra -Werror -Wno-unused-function -c -I../libc sh.c -o sh.o
ld -T link.ld -melf_i386 sh.o -L../libc -lc -o sh
make[1]: *** [Makefile:18: sh] Segmentation fault (core dumped)
make[1]: *** Deleting file 'sh'
make: *** [Makefile:51: build_apps] Error 2
```

**Comment by jferard** [comment]
Same issue. I tried to add `-ignore-unresolved-symbol _GLOBAL_OFFSET_TABLE_` to the `LDFLAGS` in `apps/Makefile`. It worked but had an unexpected result: a grub error "error 28 selected item cannot fit into memory". After some digging, I manage to find what was happening: PIE is enabled by default since Ubuntu 16.10. PIE means "position independant executable" and generate some symbols that are loaded above 3GB in the *physical memory*: 

    jferard@jferard-Z170XP-SLI:~/prog/c/aenix/src$ objdump -x kernel/kernel.elf | more

    ...
      1 .text.__x86.get_pc_thunk.ax 00000004  c01072cc  c01072cc  000102cc  2**0
                      CONTENTS, ALLOC, LOAD, READONLY, CODE
      2 .text.__x86.get_pc_thunk.bx 00000004  c01072d0  c01072d0  000102d0  2**0
                      CONTENTS, ALLOC, LOAD, READONLY, CODE
      3 .text.__x86.get_pc_thunk.dx 00000004  c01072d4  c01072d4  000102d4  2**0
                      CONTENTS, ALLOC, LOAD, READONLY, CODE
      4 .text.__x86.get_pc_thunk.cx 00000004  c01072d8  c01072d8  000102d8  2**0
                      CONTENTS, ALLOC, LOAD, READONLY, CODE
    ...

I don't know how to relocate them properly. I decided to switch to a cross-compiler:

    sudo apt install gcc-x86-64-linux-gnux32 gcc-multilib-x86-64-linux-gnux32

And then to replace:

* `CC = gcc` by `CC = x86_64-linux-gnux32-gcc`
* `ld` by `LD = x86_64-linux-gnux32-ld`
* `ar` by `AR = x86_64-linux-gnux32-ar`

It works fine.

More on cross compilers: https://wiki.osdev.org/GCC_Cross-Compiler.
